version: "3.9"

services:
  postgres:
    image: postgres:16.0-alpine
    container_name: postgres
    environment:
        POSTGRES_DB: database
        POSTGRES_USER: administrador
        POSTGRES_PASSWORD: 123456
    volumes:
        - postgres_data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    networks:
        - application
        
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
        - "5672:5672" #Porta para comunicação AMQP (Spring Boot)
        - "15672:15672" # Porta da interface de administração
    environment:
        RABBITMQ_DEFAULT_USER: administrador
        RABBITMQ_DEFAULT_PASS: admin123
    networks:
        - application

volumes:
    postgres_data:

networks:
  application:
    driver: bridge
